/**
 * Single source of truth for site-wide constants.
 * Used by root metadata, JSON-LD schema, sitemap, robots, Nav and Footer
 * so SEO data never drifts between files.
 */
export const site = {
  name: "Chronexa",
  legalName: "Chronexa",
  // Production origin. Override via NEXT_PUBLIC_SITE_URL in Vercel if needed.
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://chronexa.io",
  title: "Custom Enterprise AI for Law Firms, CPA Practices & Finance Teams | Chronexa",
  description:
    "Chronexa builds custom, secure AI systems for law firms, CPA practices, and finance teams — deployed inside your own environment, owned by you, scoped at a fixed price with a 90-day ROI guarantee.",
  tagline: "Custom Enterprise AI for Regulated Industries",
  email: "info@chronexa.io",
  locality: "IXC — India",
  hours: "Mon–Sat: 9:00am – 8:30pm",
  // Primary conversion: every "Book/Get a Free Audit" CTA opens this booking.
  booking: "https://cal.com/chronexa/30min",
  calLink: "chronexa/30min",
  ogImage: "/opengraph-image", // dynamically generated by app/opengraph-image.tsx
  twitterHandle: "@chronexa0607",
  socials: {
    linkedin: "https://www.linkedin.com/company/chronexaai/",
    twitter: "https://x.com/chronexa0607",
    instagram: "https://www.instagram.com/chronexa.io/",
  },
} as const;

/**
 * Founders / leadership — used on /about and in Organization `founder` Person
 * schema (E-E-A-T). `credential` + `expertise` (knowsAbout) + `linkedin` (sameAs)
 * are the signals Google and AI answer engines use to attribute authority.
 * NOTE: `linkedin` is left empty until the real personal profile URLs are added.
 */
export type Founder = {
  name: string;
  role: string;
  image: string;
  credential: string;
  expertise: string[];
  bio: string;
  linkedin?: string;
};

export const founders: Founder[] = [
  {
    name: "Abhishek Walia",
    role: "Co-founder & CEO",
    image: "/images/team-abhishek.png",
    credential: "Chartered Accountant (India)",
    expertise: ["Business strategy", "Financial technology", "Automation ROI", "Enterprise operations"],
    bio: "Abhishek is a Chartered Accountant (India) and Chronexa's founder-CEO, leading the company for the past three-plus years. His background spans financial technology and high-tech product development, including startups he built and ran himself. He owns Chronexa's strategy and client partnerships — translating complex operational goals into automation programs that deliver measurable ROI for clients across multiple industries.",
    linkedin: "https://www.linkedin.com/in/abhishek-walia-0710/",
  },
  {
    name: "Ankit Dhiman",
    role: "Co-founder & CTO",
    image: "/images/team-ankit.png",
    credential: "10+ years in software & AI engineering",
    expertise: ["n8n workflow automation", "AI agents", "Enterprise AI systems", "Fintech & SaaS architecture"],
    bio: "Ankit is Chronexa's co-founder and CTO, with 10+ years engineering software and AI products across fintech, real estate, construction, B2B, and SaaS. He has architected and deployed enterprise-grade AI workflows and agentic systems in production, and leads technical delivery end to end. His north star is ROI: every system is designed around the time it saves and the efficiency it unlocks — not novelty for its own sake.",
    linkedin: "https://www.linkedin.com/in/ankitdhiman65/",
  },
  {
    name: "Tushar Kaushik",
    role: "Co-founder & CMO",
    image: "/images/team-tushar.png",
    credential: "B2B marketing & demand generation",
    expertise: ["Demand generation", "B2B marketing", "Brand strategy", "Go-to-market"],
    bio: "Tushar is Chronexa's co-founder and CMO — a marketer from day one who owns demand generation, brand, and go-to-market strategy. He builds the inbound engine that connects Chronexa's engineering depth to the teams who need it.",
    linkedin: "https://www.linkedin.com/in/tushar-kaushik-2452513b0/",
  },
];

/** Approx. company facts for schema + About. foundingYear from CEO tenure (~3–4 yrs). */
export const company = {
  foundingYear: "2022",
  teamDescriptor: "a senior team of automation engineers, AI specialists, and go-to-market operators",
} as const;

/** Primary navigation — mirrors the live Framer site. */
export const navLinks = [
  { label: "Solutions", href: "/solutions" },
  { label: "Portfolio", href: "/case-studies" },
  { label: "Blog", href: "/blog" },
  { label: "About", href: "/about" },
] as const;

/**
 * The five deep-niche commercial SEO landing pages (flat keyword-first slugs).
 * Old /services/* paths 301-redirect to these (see next.config.ts).
 */
export const servicePages = [
  {
    slug: "legal-due-diligence-automation",
    oldSlug: "legal-due-diligence",
    title: "Legal Due Diligence Automation",
    nav: "Legal Due Diligence",
  },
  {
    slug: "insurance-claims-triage-automation",
    oldSlug: "insurance-claims-triage",
    title: "Insurance Claims Triage Automation",
    nav: "Insurance Claims Triage",
  },
  {
    slug: "cpa-tax-document-automation",
    oldSlug: "accounting-data-ingestion",
    title: "CPA Workflow & Tax Document Automation",
    nav: "CPA & Tax Documents",
  },
  {
    slug: "property-management-automation",
    oldSlug: "property-management-automation",
    title: "Property Management Workflow Automation",
    nav: "Property Management",
  },
  {
    slug: "vc-pe-crm-automation",
    oldSlug: "vc-pe-crm-automation",
    title: "VC & PE CRM Deal Flow Automation",
    nav: "VC & PE CRM",
  },
] as const;
