/**
 * Single source of truth for site-wide constants.
 * Used by root metadata, JSON-LD schema, sitemap, robots, Nav and Footer
 * so SEO data never drifts between files.
 */
export const site = {
  name: "Chronexa",
  legalName: "Chronexa",
  // Production origin. Override via NEXT_PUBLIC_SITE_URL in Vercel if needed.
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://chronexa.io",
  title: "Custom Enterprise AI for Law Firms, CPA Practices & Finance Teams | Chronexa",
  description:
    "Chronexa is an AI automation agency that builds custom AI infrastructure inside your own environment — intelligent document processing, sales and support automation, secure private-LLM deployments — for financial services, legal, insurance and private equity. Growth without adding headcount: fixed-price scopes, systems you own outright.",
  tagline: "Custom Enterprise AI for Regulated Industries",
  email: "info@chronexa.io",
  locality: "IXC, India",
  hours: "Mon–Sat: 9:00am – 8:30pm",
  // Primary conversion: every "Book/Get a Free Audit" CTA opens this booking.
  booking: "https://calendly.com/ankit-chronexa/30min",
  calLink: "ankit-chronexa/30min",
  ogImage: "/opengraph-image", // dynamically generated by app/opengraph-image.tsx
  twitterHandle: "@chronexa0607",
  socials: {
    linkedin: "https://www.linkedin.com/company/chronexaai/",
    twitter: "https://x.com/chronexa0607",
    instagram: "https://www.instagram.com/chronexa.io/",
  },
} as const;

/**
 * Founders / leadership — used on /about and in Organization `founder` Person
 * schema (E-E-A-T). `credential` + `expertise` (knowsAbout) + `linkedin` (sameAs)
 * are the signals Google and AI answer engines use to attribute authority.
 * NOTE: `linkedin` is left empty until the real personal profile URLs are added.
 */
export type Founder = {
  name: string;
  role: string;
  image: string;
  credential: string;
  expertise: string[];
  bio: string;
  linkedin?: string;
};

export const founders: Founder[] = [
  {
    name: "Abhishek Walia",
    role: "Co-founder & CEO",
    image: "/images/team-abhishek.png",
    credential: "Chartered Accountant (India)",
    expertise: ["Business strategy", "Financial technology", "Automation ROI", "Enterprise operations"],
    bio: "Abhishek drives Chronexa's strategic vision and client partnerships. With a background as a Chartered Accountant and tech entrepreneur, he bridges the gap between complex enterprise operations and AI automation. He ensures every system we build translates directly into measurable ROI for our clients.",
    linkedin: "https://www.linkedin.com/in/abhishek-walia-0710/",
  },
  {
    name: "Ankit Dhiman",
    role: "Co-founder & CTO",
    image: "/images/team-ankit.png",
    credential: "10+ years in software & AI engineering",
    expertise: ["n8n workflow automation", "AI agents", "Enterprise AI systems", "Fintech & SaaS architecture"],
    bio: "Ankit leads technical delivery, bringing 10+ years of software and AI engineering experience. He architects secure, enterprise-grade AI systems and agentic workflows. His focus is on shipping stable, production-ready infrastructure that genuinely saves time and accelerates business operations.",
    linkedin: "https://www.linkedin.com/in/ankitdhiman65/",
  },
  {
    name: "Tushar Kaushik",
    role: "Co-founder & CMO",
    image: "/images/team-tushar.png",
    credential: "B2B marketing & demand generation",
    expertise: ["Demand generation", "B2B marketing", "Brand strategy", "Go-to-market"],
    bio: "Tushar heads Chronexa's brand and demand generation strategy. As a seasoned B2B marketer, he builds the growth engines that connect our deep engineering capabilities with the enterprise teams that need them most, ensuring our solutions reach the right markets.",
    linkedin: "https://www.linkedin.com/in/tushar-kaushik-2452513b0/",
  },
];

/** Approx. company facts for schema + About. foundingYear from CEO tenure (~3–4 yrs). */
export const company = {
  foundingYear: "2022",
  teamDescriptor: "a senior team of automation engineers, AI specialists, and go-to-market operators",
} as const;

/** Primary navigation — mirrors the live Framer site. */
export const navLinks = [
  { label: "Solutions", href: "/solutions" },
  { label: "Portfolio", href: "/case-studies" },
  { label: "Blog", href: "/blog" },
  { label: "About", href: "/about" },
] as const;

/**
 * The five deep-niche commercial SEO landing pages (flat keyword-first slugs).
 * Old /services/* paths 301-redirect to these (see next.config.ts).
 */
export const servicePages = [
  {
    slug: "legal-due-diligence-automation",
    oldSlug: "legal-due-diligence",
    title: "Legal Due Diligence Automation",
    nav: "Legal Due Diligence",
  },
  {
    slug: "insurance-claims-triage-automation",
    oldSlug: "insurance-claims-triage",
    title: "Insurance Claims Triage Automation",
    nav: "Insurance Claims Triage",
  },
  {
    slug: "cpa-tax-document-automation",
    oldSlug: "accounting-data-ingestion",
    title: "CPA Workflow & Tax Document Automation",
    nav: "CPA & Tax Documents",
  },
  {
    slug: "property-management-automation",
    oldSlug: "property-management-automation",
    title: "Property Management Workflow Automation",
    nav: "Property Management",
  },
  {
    slug: "vc-pe-crm-automation",
    oldSlug: "vc-pe-crm-automation",
    title: "VC & PE CRM Deal Flow Automation",
    nav: "VC & PE CRM",
  },
] as const;
